### ISSUE TITLE
Sameersbn/Openfire

### ISSUE THREAD

**Issue by lispeedyg** [gizmotronic/docker-openfire#1]
Hi,
I'm new to docker implementations.
However, I've been using Sameer's implementation on my Synology Container.  I see that your's is much more updated.  Is there a way to replace Sameer's docker image with all it's settings to yours?

Sorry if this is so basic.  But, as I mentioned, I'm very new to images.
Thanks,
Gus

**Comment by gizmotronic** [comment]
I don't have any experience with Synology devices. What I can say is that in order to do this, you need to have a Docker volume mapped to /var/lib/openfire in the container. You may use the same volume with this image that you did with sameersbn/openfire.

One place you could run into trouble is the database. The embedded HSQL database is not intended for production use, so I've always used Openfire with an external database. If you chose the embedded database during initial setup and it doesn't work properly, I'm afraid I am not going to be of any help.
